
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'artix7.ucf'
####################################################################################

# ??申?申N??申?申??申?申??申?申b??申?申N??申?申??申?申UCF??申?申L??申?申q


# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent


create_clock -name CLK -period 20.000 [get_ports CLK]
set_property PACKAGE_PIN C11 [get_ports CLK]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'CLK' has been applied to the port object 'CLK'.
set_property IOSTANDARD LVCMOS33 [get_ports CLK]


#-------------------------------------------------------------------------------------
# LED??申?申??申?申v??申?申b??申?申V??申?申??申?申SW??申?申??申?申UCF??申?申L??申?申q
#-------------------------------------------------------------------------------------
set_property PACKAGE_PIN M2 [get_ports BUTTON_N]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'BUTTON_N' has been applied to the port object 'BUTTON_N'.
set_property IOSTANDARD LVCMOS33 [get_ports BUTTON_N]
set_property PACKAGE_PIN V1 [get_ports {LED[0]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[0]' has been applied to the port object 'LED[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN U1 [get_ports {LED[1]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[1]' has been applied to the port object 'LED[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN T1 [get_ports {LED[2]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[2]' has been applied to the port object 'LED[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN R1 [get_ports {LED[3]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[3]' has been applied to the port object 'LED[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN N2 [get_ports {LED[4]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[4]' has been applied to the port object 'LED[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN N1 [get_ports {LED[5]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[5]' has been applied to the port object 'LED[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN M1 [get_ports {LED[6]}]

# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[6]' has been applied to the port object 'LED[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]

#set_false_path -through [get_nets RST]

#set_property PACKAGE_PIN J18 [get_ports {LED[0]}]
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED[0]' has been applied to the port object 'LED[0]'.
#set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]






